#!/usr/bin/env python3
"""Validate the Ad Remaker Hermes profile distribution and its Claude Code and Codex plugins."""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path
from typing import Any
from urllib.parse import parse_qsl, urlsplit

try:
    import yaml  # type: ignore
except ImportError:  # PyYAML is optional.
    yaml = None

ROOT = Path(__file__).resolve().parents[1]

REQUIRED_FILES = (
    ".codex-plugin/plugin.json",
    "docs/decisions/ADR-005-codex-skills-only.md",
    "scripts/export_codex_package.py",
    "scripts/sync_skill_rules.py",
    "tests/check_codex.py",
    "tests/check_codex_chat.py",
    "tests/codex_guard.py",
    ".claude-plugin/marketplace.json",
    ".claude-plugin/plugin.json",
    ".gitignore",
    ".mcp.json",
    "AGENTS.md",
    "LICENSE",
    "README.md",
    "SOUL.md",
    "agents/ad-remaker.md",
    "config.yaml",
    "cron/jobs.json",
    "distribution.yaml",
    "docs/ad-remaker-complete-operating-report.md",
    "docs/architecture.md",
    "docs/decisions/ADR-001-profile-distribution.md",
    "docs/decisions/ADR-002-provider-skill-layers.md",
    "docs/decisions/ADR-003-claude-code-plugin.md",
    "docs/decisions/ADR-004-ffmpeg-skill-claude-code-only.md",
    "docs/decisions/README.md",
    "docs/provenance/README.md",
    "docs/provenance/brandsearch.md",
    "docs/provenance/fal.md",
    "docs/provenance/higgsfield.md",
    "docs/provenance/kie-ai.md",
    "docs/provenance/pika.md",
    "docs/provenance/trendtrack.md",
    "docs/service-matrix.md",
    "scripts/install_provider_skills.sh",
    "scripts/sync_claude_agent.py",
    "scripts/validate_distribution.py",
    "skills/README.md",
    "skills/winning-ad-remake-workflow/SKILL.md",
    "skills/winning-ad-remake-workflow/references/upstream.md",
    "skills/free-fallback-mode/SKILL.md",
    "skills/free-fallback-mode/scripts/_media.py",
    "skills/free-fallback-mode/scripts/cut_list.py",
    "skills/free-fallback-mode/scripts/first_three_seconds_sheet.py",
    "skills/free-fallback-mode/scripts/frame_sheet.py",
    "skills/free-fallback-mode/scripts/shot_clips.py",
    "skills/meta-ads-usage/SKILL.md",
    "skills/provider-policy/SKILL.md",
    "skills/providers/SKILL.md",
    "tests/README.md",
    "tests/check_mcp_fixtures.py",
    "tests/fixtures/README.md",
    "tests/smoke.sh",
    "tests/smoke_chat.py",
    "tests/smoke_session.py",
    "tests/check_smoke_regressions.py",
)

FORBIDDEN_REPORT = "docs/ad-remaker-fonctionnement-complet.md"

# Removed by ADR-002; their source texts live in docs/provenance/.
REMOVED_SKILLS = (
    "brandsearch-usage",
    "fal-usage",
    "higgsfield-usage",
    "kie-ai-usage",
    "pika-usage",
    "trendtrack-usage",
)

PROVIDER_PINS_FILE = "skills/providers/SKILL.md"
PROVIDER_PINS_BEGIN = "<!-- provider-pins:begin -->"
PROVIDER_PINS_END = "<!-- provider-pins:end -->"
PROVIDER_PINS_HEADER = ["Vendor", "Repository", "Skill path", "Pinned ref", "Install", "License", "Checked"]
PROVIDER_INSTALL_VALUES = {"hermes", "no"}
PROVIDER_VENDORS = {"brandsearch", "ffmpeg-skill", "fal", "higgsfield", "kie-ai", "meta-ads", "pika", "trendtrack"}

# Claude Code plugin (ADR-003). The subagent body is SOUL.md, generated by
# scripts/sync_claude_agent.py; the plugin version follows distribution.yaml.
PLUGIN_NAME = "ad-remaker"
PLUGIN_MANIFEST = ".claude-plugin/plugin.json"
PLUGIN_MARKETPLACE = ".claude-plugin/marketplace.json"
PLUGIN_MCP = ".mcp.json"
PLUGIN_AGENT = "agents/ad-remaker.md"
SOUL_FILE = "SOUL.md"
FORBIDDEN_FILE_NAMES = {
    ".env",
    "auth.json",
    "credentials.json",
    "secrets.json",
    "state.db",
}
FORBIDDEN_SUFFIXES = {".db", ".sqlite", ".sqlite3", ".log"}
FORBIDDEN_ROOT_DIRS = {
    ".worktrees",
    "audio_cache",
    "backups",
    "browser-profile",
    "browser_profiles",
    "browser_screenshots",
    "cache",
    "checkpoints",
    "document_cache",
    "hermes-agent",
    "home",
    "image_cache",
    "local",
    "logs",
    "mcp-tokens",
    "memories",
    "memory",
    "plans",
    "platforms",
    "profiles",
    "proxy",
    "sandboxes",
    "sessions",
    "state",
    "vault",
    "workspace",
}
IGNORED_DIRS = {".git", ".pytest_cache", "__pycache__"}

# Hermes reads MCP servers from config.yaml `mcp_servers`. Values under these
# keys must be `${ENV_VAR}` placeholders (optionally prefixed by "Bearer ").
SENSITIVE_KEY = re.compile(r"(authorization|token|secret|password|passwd|cookie|api[_-]?key|apikey)", re.IGNORECASE)
PLACEHOLDER = re.compile(r"\$\{([^}]+)\}")
# Name segments that make a URL query parameter or command-line flag carry a
# secret (`?api_key=`, `--auth`, `--key=`), unless the name ends in a segment
# that describes the secret instead of holding it (`--auth-type`, `--token-file`).
SECRET_NAME_SEGMENTS = {"auth", "key"}
NON_SECRET_NAME_SUFFIXES = {"env", "file", "header", "method", "mode", "name", "path", "type", "url", "var"}
# Hermes resolves these Cursor-style context variables itself; they are not env vars.
CONTEXT_PLACEHOLDERS = {"userHome", "workspaceFolder", "workspaceFolderBasename", "pathSeparator", "/"}
TOKEN_SHAPE = re.compile(
    r"(\bBearer\s+(?!\$\{)\S+"
    r"|\b(?:sk|pk|rk)[-_][A-Za-z0-9_-]{8,}"
    r"|\bdk_[A-Za-z0-9_-]{8,}"
    r"|\bgh[pousr]_[A-Za-z0-9]{20,}"
    r"|\bEAA[A-Za-z0-9]{20,}"
    r"|\bAKIA[0-9A-Z]{16})"
)


def fail(errors: list[str], message: str) -> None:
    errors.append(message)


def load_json(relative_path: str, errors: list[str]) -> Any:
    path = ROOT / relative_path
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except (OSError, UnicodeError, json.JSONDecodeError) as exc:
        fail(errors, f"{relative_path}: invalid JSON: {exc}")
        return None


def fallback_scalar(raw_value: str) -> Any:
    value = raw_value.strip()
    if value[:1] in {"'", '"'}:
        quote = value[0]
        closing = value.find(quote, 1)
        return value[1:closing] if closing > 0 else value[1:]
    value = re.sub(r"\s+#.*$", "", value)
    if value == "[]":
        return []
    if value == "{}":
        return {}
    if value.lower() in {"true", "false"}:
        return value.lower() == "true"
    if value.lower() in {"", "~", "null"}:
        return None
    if re.fullmatch(r"-?[0-9]+", value):
        return int(value)
    return value


def fallback_yaml_mapping(text: str, relative_path: str, errors: list[str]) -> dict[str, Any] | None:
    """Parse the block-style YAML subset used by this distribution, without PyYAML.

    Supports nested mappings, lists of scalars or mappings, quoted and plain
    scalars, and comments. Flow collections other than `[]` and `{}` are not
    supported.
    """
    lines: list[tuple[int, str, int]] = []
    for line_number, raw_line in enumerate(text.splitlines(), start=1):
        if not raw_line.strip() or raw_line.lstrip().startswith("#"):
            continue
        lines.append((len(raw_line) - len(raw_line.lstrip(" ")), raw_line.strip(), line_number))

    class ParseError(Exception):
        pass

    def parse_block(index: int, indent: int) -> tuple[Any, int]:
        if lines[index][1].startswith("-"):
            return parse_list(index, indent)
        return parse_mapping(index, indent)

    def parse_nested(index: int, indent: int) -> tuple[Any, int]:
        """Parse the value of a key whose scalar part is empty."""
        if index < len(lines):
            next_indent, next_content, _ = lines[index]
            if next_indent > indent or (next_indent == indent and next_content.startswith("- ")):
                return parse_block(index, next_indent)
        return None, index

    def parse_mapping(index: int, indent: int) -> tuple[dict[str, Any], int]:
        result: dict[str, Any] = {}
        while index < len(lines) and lines[index][0] == indent and not lines[index][1].startswith("- "):
            _, content, line_number = lines[index]
            match = re.match(r"^([A-Za-z_][A-Za-z0-9_-]*):(?:\s+(.*))?$", content)
            if not match:
                raise ParseError(f"{relative_path}:{line_number}: unsupported or invalid YAML")
            key, raw_value = match.groups()
            if raw_value and not raw_value.lstrip().startswith("#"):
                result[key] = fallback_scalar(raw_value)
                index += 1
            else:
                result[key], index = parse_nested(index + 1, indent)
        if index < len(lines) and lines[index][0] > indent:
            raise ParseError(f"{relative_path}:{lines[index][2]}: unexpected indentation")
        return result, index

    def parse_list(index: int, indent: int) -> tuple[list[Any], int]:
        result: list[Any] = []
        while index < len(lines) and lines[index][0] == indent and lines[index][1].startswith("-"):
            _, content, line_number = lines[index]
            item = content[1:].lstrip()
            if not item:
                value, index = parse_nested(index + 1, indent)
                result.append(value)
            elif re.match(r"^[A-Za-z_][A-Za-z0-9_-]*:(\s|$)", item):
                # A mapping that starts on the dash line: re-anchor it at the key column.
                item_indent = indent + len(content) - len(item)
                lines[index] = (item_indent, item, line_number)
                value, index = parse_mapping(index, item_indent)
                result.append(value)
            else:
                result.append(fallback_scalar(item))
                index += 1
        return result, index

    if not lines:
        return {}
    try:
        data, index = parse_block(0, lines[0][0])
        if index < len(lines):
            raise ParseError(f"{relative_path}:{lines[index][2]}: unsupported or invalid YAML")
    except ParseError as exc:
        fail(errors, str(exc))
        return None
    return data


def load_yaml_mapping(relative_path: str, errors: list[str]) -> dict[str, Any] | None:
    path = ROOT / relative_path
    try:
        text = path.read_text(encoding="utf-8")
    except (OSError, UnicodeError) as exc:
        fail(errors, f"{relative_path}: cannot read YAML: {exc}")
        return None

    if yaml is None:
        data = fallback_yaml_mapping(text, relative_path, errors)
    else:
        try:
            data = yaml.safe_load(text)
        except yaml.YAMLError as exc:
            fail(errors, f"{relative_path}: invalid YAML: {exc}")
            return None

    if not isinstance(data, dict):
        fail(errors, f"{relative_path}: top-level YAML value must be a mapping")
        return None
    return data


def validate_required_files(errors: list[str]) -> None:
    for relative_path in REQUIRED_FILES:
        path = ROOT / relative_path
        if not path.is_file():
            fail(errors, f"missing required file: {relative_path}")
        elif path.stat().st_size == 0:
            fail(errors, f"required file is empty: {relative_path}")

    if (ROOT / FORBIDDEN_REPORT).exists():
        fail(errors, f"obsolete French-facing report path must not exist: {FORBIDDEN_REPORT}")


def walk_strings(value: Any, path: tuple[str, ...] = ()):
    if isinstance(value, str):
        yield path, value
    elif isinstance(value, dict):
        for key, child in value.items():
            yield from walk_strings(child, path + (str(key),))
    elif isinstance(value, list):
        for index, child in enumerate(value):
            yield from walk_strings(child, path + (str(index),))


def is_secret_name(name: str) -> bool:
    segments = [segment for segment in re.split(r"[-_.]", name.lower().lstrip("-")) if segment]
    if not segments or segments[-1] in NON_SECRET_NAME_SUFFIXES:
        return False
    return bool(SENSITIVE_KEY.search(name)) or any(segment in SECRET_NAME_SEGMENTS for segment in segments)


def is_literal(value: str) -> bool:
    """True when the value holds anything besides `${VAR}` placeholders."""
    return bool(PLACEHOLDER.sub("", value).strip())


def url_secret_issues(value: str) -> list[str]:
    """Literal credentials carried by a URL: userinfo password or secret-named query parameters."""
    if not re.match(r"^[A-Za-z][A-Za-z0-9+.-]*://", value):
        return []
    try:
        parts = urlsplit(value)
        password = parts.password
    except ValueError:
        return []
    issues = []
    if password and is_literal(password):
        issues.append("URL userinfo carries a literal password")
    for key, query_value in parse_qsl(parts.query, keep_blank_values=True):
        if is_secret_name(key) and is_literal(query_value):
            issues.append(f"URL query parameter {key!r} carries a literal secret")
    return issues


def args_secret_issues(args: list[Any]) -> list[str]:
    """Literal values passed to secret-named flags: `--api-key VALUE` or `--api-key=VALUE`."""
    issues = []
    for index, item in enumerate(args):
        if not isinstance(item, str) or not item.startswith("-"):
            continue
        flag, separator, inline_value = item.partition("=")
        if not is_secret_name(flag):
            continue
        if separator:
            value = inline_value
        elif index + 1 < len(args) and isinstance(args[index + 1], str) and not args[index + 1].startswith("-"):
            value = args[index + 1]
        else:
            continue
        if is_literal(value):
            issues.append(f"args flag {flag!r} carries a literal secret")
    return issues


def validate_mcp_servers(config: dict[str, Any], env_names: set[str], label: str, errors: list[str]) -> None:
    """Every declared server must ship disabled, secret-free, and with declared env vars."""
    servers = config.get("mcp_servers")
    if servers is None:
        return
    if not isinstance(servers, dict):
        fail(errors, f"{label}: 'mcp_servers' must be a mapping")
        return

    for name, server in servers.items():
        prefix = f"{label}: mcp_servers.{name}"
        if not isinstance(server, dict):
            fail(errors, f"{prefix}: must be a mapping")
            continue
        url = server.get("url")
        if "command" not in server and not (isinstance(url, str) and url.startswith("https://")):
            fail(errors, f"{prefix}: 'url' must be an https:// URL")
        # Hermes treats a missing or unrecognized value as enabled.
        if server.get("enabled") is not False:
            fail(errors, f"{prefix}: 'enabled' must be false; users enable servers in their installed profile")
        validate_server_secrets(server, env_names, prefix, errors)


def validate_server_secrets(server: dict[str, Any], env_names: set[str], prefix: str, errors: list[str]) -> None:
    """No literal secret in a server entry, and every `${VAR}` declared in env_requires."""
    args = server.get("args")
    if isinstance(args, list):
        for issue in args_secret_issues(args):
            fail(errors, f"{prefix}.args: {issue}; use an ${{ENV_VAR}} placeholder or OAuth")

    for path, value in walk_strings(server):
        dotted = ".".join(path)
        for issue in url_secret_issues(value):
            fail(errors, f"{prefix}.{dotted}: {issue}; use an ${{ENV_VAR}} placeholder or OAuth")
        if any(SENSITIVE_KEY.search(part) for part in path):
            literal = PLACEHOLDER.sub("", value).strip()
            if literal and literal.lower() != "bearer":
                fail(errors, f"{prefix}.{dotted}: literal secret; use an ${{ENV_VAR}} placeholder or OAuth")
                continue
        if TOKEN_SHAPE.search(value):
            fail(errors, f"{prefix}.{dotted}: value looks like a hardcoded token")
        for reference in PLACEHOLDER.findall(value):
            reference = reference.strip()
            if reference.startswith("env:"):
                reference = reference[len("env:"):].strip()
            if reference not in CONTEXT_PLACEHOLDERS and reference not in env_names:
                fail(errors, f"{prefix}.{dotted}: ${{{reference}}} is not declared in distribution.yaml env_requires")


def validate_yaml_files(errors: list[str], config_path: str = "config.yaml") -> None:
    env_names: set[str] = set()
    manifest = load_yaml_mapping("distribution.yaml", errors)
    if manifest is not None:
        required = {
            "name": str,
            "version": str,
            "description": str,
            "hermes_requires": str,
            "author": str,
            "license": str,
            "env_requires": list,
        }
        for key, expected_type in required.items():
            if key not in manifest:
                fail(errors, f"distribution.yaml: missing required key {key!r}")
            elif not isinstance(manifest[key], expected_type):
                fail(errors, f"distribution.yaml: {key!r} must be {expected_type.__name__}")
        if manifest.get("name") != "ad-remaker":
            fail(errors, "distribution.yaml: 'name' must be 'ad-remaker'")
        for entry in manifest.get("env_requires") or []:
            if not isinstance(entry, dict) or not isinstance(entry.get("name"), str) or not entry["name"].strip():
                fail(errors, "distribution.yaml: each env_requires entry must be a mapping with a 'name'")
                continue
            env_names.add(entry["name"].strip())
            if entry.get("required") is not False:
                fail(errors, f"distribution.yaml: env_requires {entry['name']!r} must set 'required: false'")

    config = load_yaml_mapping(config_path, errors)
    if config is not None:
        for key in ("agent", "approvals", "security"):
            if key not in config:
                fail(errors, f"{config_path}: missing required top-level mapping {key!r}")
            elif not isinstance(config[key], dict):
                fail(errors, f"{config_path}: {key!r} must be a mapping")
        validate_mcp_servers(config, env_names, config_path, errors)


def validate_json_files(errors: list[str]) -> None:
    jobs = load_json("cron/jobs.json", errors)
    if jobs is not None:
        if not isinstance(jobs, dict):
            fail(errors, "cron/jobs.json: top-level value must be an object")
        elif not isinstance(jobs.get("jobs"), list):
            fail(errors, "cron/jobs.json: 'jobs' must be an array")


def parse_skill_frontmatter(path: Path, errors: list[str]) -> dict[str, Any] | None:
    relative_path = path.relative_to(ROOT).as_posix()
    try:
        text = path.read_text(encoding="utf-8")
    except (OSError, UnicodeError) as exc:
        fail(errors, f"{relative_path}: cannot read Skill: {exc}")
        return None

    lines = text.splitlines()
    if not lines or lines[0].strip() != "---":
        fail(errors, f"{relative_path}: Skill must begin with YAML frontmatter")
        return None
    try:
        closing_index = next(index for index, line in enumerate(lines[1:], start=1) if line.strip() == "---")
    except StopIteration:
        fail(errors, f"{relative_path}: Skill frontmatter has no closing delimiter")
        return None

    frontmatter_text = "\n".join(lines[1:closing_index])
    if yaml is not None:
        try:
            data = yaml.safe_load(frontmatter_text)
        except yaml.YAMLError as exc:
            fail(errors, f"{relative_path}: invalid Skill frontmatter: {exc}")
            return None
        if not isinstance(data, dict):
            fail(errors, f"{relative_path}: Skill frontmatter must be a mapping")
            return None
        return data

    data: dict[str, Any] = {}
    for key in ("name", "description"):
        match = re.search(rf"(?m)^{key}:\s*(.+?)\s*$", frontmatter_text)
        if match:
            data[key] = match.group(1).strip("\"'")
    return data


def validate_skills(errors: list[str]) -> None:
    skills_dir = ROOT / "skills"
    if not skills_dir.is_dir():
        fail(errors, "missing required directory: skills")
        return

    skill_directories = sorted(path for path in skills_dir.iterdir() if path.is_dir() and not path.name.startswith("."))
    if not skill_directories:
        fail(errors, "skills: at least one Skill directory is required")
        return

    for skill_dir in skill_directories:
        skill_file = skill_dir / "SKILL.md"
        relative_skill = skill_file.relative_to(ROOT).as_posix()
        if not skill_file.is_file():
            fail(errors, f"missing Skill entry point: {relative_skill}")
            continue
        metadata = parse_skill_frontmatter(skill_file, errors)
        if metadata is None:
            continue
        for key in ("name", "description"):
            value = metadata.get(key)
            if not isinstance(value, str) or not value.strip():
                fail(errors, f"{relative_skill}: frontmatter {key!r} must be a non-empty string")
        if metadata.get("name") != skill_dir.name:
            fail(errors, f"{relative_skill}: frontmatter name must match directory name {skill_dir.name!r}")

    for name in REMOVED_SKILLS:
        if (skills_dir / name).exists():
            fail(errors, f"skills/{name}: removed by ADR-002; use provider-policy and providers instead")


def validate_provider_pins(errors: list[str]) -> None:
    """Check the pin table that scripts/install_provider_skills.sh reads."""
    path = ROOT / PROVIDER_PINS_FILE
    try:
        text = path.read_text(encoding="utf-8")
    except (OSError, UnicodeError) as exc:
        fail(errors, f"{PROVIDER_PINS_FILE}: cannot read pin table: {exc}")
        return
    if text.count(PROVIDER_PINS_BEGIN) != 1 or text.count(PROVIDER_PINS_END) != 1:
        fail(errors, f"{PROVIDER_PINS_FILE}: pin table markers must appear exactly once")
        return
    block = text.split(PROVIDER_PINS_BEGIN, 1)[1].split(PROVIDER_PINS_END, 1)[0]
    table = [line.strip() for line in block.splitlines() if line.strip().startswith("|")]
    if len(table) < 2 or [cell.strip() for cell in table[0].strip("|").split("|")] != PROVIDER_PINS_HEADER:
        fail(errors, f"{PROVIDER_PINS_FILE}: pin table header must be {' | '.join(PROVIDER_PINS_HEADER)}")
        return

    seen: set[str] = set()
    for line in table[2:]:
        cells = [cell.strip() for cell in line.strip("|").split("|")]
        if len(cells) != len(PROVIDER_PINS_HEADER):
            fail(errors, f"{PROVIDER_PINS_FILE}: pin row must have {len(PROVIDER_PINS_HEADER)} cells: {line}")
            continue
        vendor, repository, skill_path, ref, install, license_note, checked = cells
        where = f"{PROVIDER_PINS_FILE}: vendor {vendor!r}"
        if vendor in seen:
            fail(errors, f"{where}: duplicate row")
        seen.add(vendor)
        if not re.fullmatch(r"[a-z][a-z0-9-]*", vendor):
            fail(errors, f"{where}: vendor key must be lowercase letters, digits, and hyphens")
        if ref == "none":
            if repository != "none" or skill_path != "none":
                fail(errors, f"{where}: a row without a pin must use 'none' for repository and Skill path")
        elif re.fullmatch(r"[0-9a-f]{40}", ref):
            if not re.fullmatch(r"[A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+", repository):
                fail(errors, f"{where}: repository must be owner/name")
            if not re.fullmatch(r"[A-Za-z0-9_.-]+(/[A-Za-z0-9_.-]+)*", skill_path) or ".." in skill_path:
                fail(errors, f"{where}: Skill path must be a relative path inside the repository")
        else:
            fail(errors, f"{where}: pinned ref must be a full 40-character commit SHA or 'none'")
        if install not in PROVIDER_INSTALL_VALUES:
            fail(errors, f"{where}: Install must be one of {', '.join(sorted(PROVIDER_INSTALL_VALUES))}")
        elif install == "hermes" and ref == "none":
            fail(errors, f"{where}: Install 'hermes' requires a pinned commit")
        if not license_note:
            fail(errors, f"{where}: license note is required")
        if not re.fullmatch(r"\d{4}-\d{2}-\d{2}", checked) and not (checked == "pending" and ref == "none"):
            fail(errors, f"{where}: check date must be YYYY-MM-DD ('pending' only for a row without a pin)")

    missing = PROVIDER_VENDORS - seen
    if missing:
        fail(errors, f"{PROVIDER_PINS_FILE}: pin table is missing vendors: {', '.join(sorted(missing))}")


def render_agent(agent_text: str, soul_text: str) -> str | None:
    """Return the subagent file with its frontmatter kept and its body replaced by SOUL.md.

    The file is the frontmatter block, one blank line, then SOUL.md verbatim.
    Returns None when the file does not start with a closed frontmatter block.
    """
    if not agent_text.startswith("---\n"):
        return None
    closing = agent_text.find("\n---\n", 3)
    if closing < 0:
        return None
    return agent_text[: closing + len("\n---\n")] + "\n" + soul_text


def validate_claude_plugin(errors: list[str]) -> None:
    """Check the Claude Code plugin files against the Hermes distribution they mirror."""
    manifest = load_yaml_mapping("distribution.yaml", []) or {}
    env_names = {
        entry["name"].strip()
        for entry in manifest.get("env_requires") or []
        if isinstance(entry, dict) and isinstance(entry.get("name"), str)
    }

    plugin = load_json(PLUGIN_MANIFEST, errors)
    if plugin is not None:
        if not isinstance(plugin, dict):
            fail(errors, f"{PLUGIN_MANIFEST}: top-level value must be an object")
        else:
            if plugin.get("name") != PLUGIN_NAME:
                fail(errors, f"{PLUGIN_MANIFEST}: 'name' must be {PLUGIN_NAME!r}")
            if plugin.get("version") != manifest.get("version"):
                fail(
                    errors,
                    f"{PLUGIN_MANIFEST}: 'version' {plugin.get('version')!r} must match "
                    f"distribution.yaml version {manifest.get('version')!r}",
                )
            if not isinstance(plugin.get("description"), str) or not plugin["description"].strip():
                fail(errors, f"{PLUGIN_MANIFEST}: 'description' must be a non-empty string")
            author = plugin.get("author")
            if not isinstance(author, dict) or not isinstance(author.get("name"), str) or not author["name"].strip():
                fail(errors, f"{PLUGIN_MANIFEST}: 'author' must be an object with a 'name'")
            for key in ("agents", "skills", "mcpServers"):
                if key in plugin:
                    fail(errors, f"{PLUGIN_MANIFEST}: do not set {key!r}; the plugin uses the default agents/, skills/, and .mcp.json")

    marketplace = load_json(PLUGIN_MARKETPLACE, errors)
    if marketplace is not None:
        entries = marketplace.get("plugins") if isinstance(marketplace, dict) else None
        owner = marketplace.get("owner") if isinstance(marketplace, dict) else None
        if not isinstance(owner, dict) or not isinstance(owner.get("name"), str):
            fail(errors, f"{PLUGIN_MARKETPLACE}: 'owner' must be an object with a 'name'")
        if not isinstance(entries, list) or len(entries) != 1 or not isinstance(entries[0], dict):
            fail(errors, f"{PLUGIN_MARKETPLACE}: 'plugins' must list exactly one entry, this repository")
        else:
            entry = entries[0]
            if entry.get("name") != PLUGIN_NAME or entry.get("source") not in {"./", "."}:
                fail(errors, f"{PLUGIN_MARKETPLACE}: the entry must be named {PLUGIN_NAME!r} with source './'")
            if "version" in entry:
                fail(errors, f"{PLUGIN_MARKETPLACE}: do not set 'version' in the entry; {PLUGIN_MANIFEST} holds it")

    try:
        agent_text = (ROOT / PLUGIN_AGENT).read_text(encoding="utf-8")
        soul_text = (ROOT / SOUL_FILE).read_text(encoding="utf-8")
    except (OSError, UnicodeError) as exc:
        fail(errors, f"{PLUGIN_AGENT}: cannot compare with {SOUL_FILE}: {exc}")
    else:
        expected = render_agent(agent_text, soul_text)
        if expected is None:
            fail(errors, f"{PLUGIN_AGENT}: must begin with a closed YAML frontmatter block")
        else:
            metadata = parse_skill_frontmatter(ROOT / PLUGIN_AGENT, errors) or {}
            if metadata.get("name") != PLUGIN_NAME:
                fail(errors, f"{PLUGIN_AGENT}: frontmatter name must be {PLUGIN_NAME!r}")
            if not isinstance(metadata.get("description"), str) or not metadata["description"].strip():
                fail(errors, f"{PLUGIN_AGENT}: frontmatter 'description' must be a non-empty string")
            if expected != agent_text:
                fail(
                    errors,
                    f"{PLUGIN_AGENT}: body differs from {SOUL_FILE}; run python3 scripts/sync_claude_agent.py",
                )

    mcp = load_json(PLUGIN_MCP, errors)
    if mcp is None:
        return
    servers = mcp.get("mcpServers") if isinstance(mcp, dict) else None
    if not isinstance(servers, dict) or set(mcp) != {"mcpServers"}:
        fail(errors, f"{PLUGIN_MCP}: must be an object with a single 'mcpServers' mapping")
        return
    for name, server in servers.items():
        prefix = f"{PLUGIN_MCP}: mcpServers.{name}"
        if not isinstance(server, dict):
            fail(errors, f"{prefix}: must be an object")
            continue
        validate_server_secrets(server, env_names, prefix, errors)

    # Always compare with the distribution's own config.yaml, even when --config
    # points the Hermes checks at a test fixture.
    hermes_servers = (load_yaml_mapping("config.yaml", []) or {}).get("mcp_servers") or {}
    if not isinstance(hermes_servers, dict):
        return
    if set(servers) != set(hermes_servers):
        only_claude = ", ".join(sorted(set(servers) - set(hermes_servers))) or "none"
        only_hermes = ", ".join(sorted(set(hermes_servers) - set(servers))) or "none"
        fail(
            errors,
            f"{PLUGIN_MCP}: server set differs from config.yaml mcp_servers "
            f"(only in {PLUGIN_MCP}: {only_claude}; only in config.yaml: {only_hermes})",
        )
    for name in sorted(set(servers) & set(hermes_servers)):
        server, hermes_server = servers[name], hermes_servers[name]
        if isinstance(server, dict) and isinstance(hermes_server, dict) and server.get("url") != hermes_server.get("url"):
            fail(errors, f"{PLUGIN_MCP}: mcpServers.{name} url must match config.yaml ({hermes_server.get('url')!r})")


def validate_codex_plugin(errors: list[str]) -> None:
    manifest = load_json(".codex-plugin/plugin.json", errors)
    distribution = load_yaml_mapping("distribution.yaml", errors) or {}
    if not isinstance(manifest, dict):
        fail(errors, ".codex-plugin/plugin.json: must be an object")
    elif (manifest.get("name") != PLUGIN_NAME
          or manifest.get("version") != distribution.get("version")
          or manifest.get("skills") != "./skills"
          or manifest.get("mcpServers") != {}):
        fail(errors, ".codex-plugin/plugin.json: identity/version/skills must match and mcpServers must be explicitly empty")
    if not (ROOT / SOUL_FILE).is_file():
        return
    expected = (ROOT / SOUL_FILE).read_text(encoding="utf-8")
    for entry in sorted((ROOT / "skills").glob("*/SKILL.md")):
        reference = entry.parent / "references/agent-rules.md"
        if not reference.is_file() or reference.read_text(encoding="utf-8") != expected:
            fail(errors, f"{reference.relative_to(ROOT)}: generated rules differ from SOUL.md; run python3 scripts/sync_skill_rules.py")
        if "[the agent rules](references/agent-rules.md)" not in entry.read_text(encoding="utf-8"):
            fail(errors, f"{entry.relative_to(ROOT)}: required rule-loading link missing")


def validate_forbidden_files(errors: list[str]) -> None:
    for path in ROOT.rglob("*"):
        relative = path.relative_to(ROOT)
        if any(part in IGNORED_DIRS for part in relative.parts):
            continue
        if relative.parts and relative.parts[0] in FORBIDDEN_ROOT_DIRS:
            fail(errors, f"forbidden runtime-state path: {relative.as_posix()}")
            continue
        if not path.is_file():
            continue
        lower_name = path.name.lower()
        if lower_name in FORBIDDEN_FILE_NAMES or lower_name.startswith(".env."):
            if lower_name not in {".env.example", ".env.sample", ".env.template"}:
                fail(errors, f"forbidden secret/state file: {relative.as_posix()}")
        elif path.suffix.lower() in FORBIDDEN_SUFFIXES:
            fail(errors, f"forbidden secret/state file: {relative.as_posix()}")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--config",
        default="config.yaml",
        help="validate this file in place of the distribution's config.yaml (used by tests/check_mcp_fixtures.py)",
    )
    args = parser.parse_args(argv)
    config_path = Path(args.config).resolve() if args.config != "config.yaml" else ROOT / "config.yaml"
    try:
        config_label = config_path.relative_to(ROOT).as_posix()
    except ValueError:
        config_label = str(config_path)

    errors: list[str] = []
    validate_required_files(errors)
    validate_yaml_files(errors, config_label)
    validate_json_files(errors)
    validate_skills(errors)
    validate_provider_pins(errors)
    validate_claude_plugin(errors)
    validate_codex_plugin(errors)
    validate_forbidden_files(errors)

    if errors:
        print(f"Distribution validation failed with {len(errors)} error(s):", file=sys.stderr)
        for error in errors:
            print(f"  - {error}", file=sys.stderr)
        return 1

    parser_name = "PyYAML" if yaml is not None else "stdlib fallback"
    print(f"Distribution validation passed ({parser_name}).")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
